// <auto-generated />
using System;
using AthensWorkspace.MHWs.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AthensWorkspace.Migrations.MHWs
{
    [DbContext(typeof(MHWsDbContext))]
    [Migration("20260326173822_AddMHWsAmulet")]
    partial class AddMHWsAmulet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AthensWorkspace.MHWs.Models.Skill", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<short>("Id"));

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ExplanationByLevel")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<short>("Icon")
                        .HasColumnType("smallint");

                    b.Property<byte>("MaxLevel")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<short>("Order")
                        .HasColumnType("smallint");

                    b.Property<string>("Ruby")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.ToTable("Skill");
                });

            modelBuilder.Entity("AthensWorkspace.Models.MHWs.Amulet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("Level1")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("Level2")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte?>("Level3")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("Rare")
                        .HasColumnType("tinyint unsigned");

                    b.Property<short>("SkillId1")
                        .HasColumnType("smallint");

                    b.Property<short>("SkillId2")
                        .HasColumnType("smallint");

                    b.Property<short?>("SkillId3")
                        .HasColumnType("smallint");

                    b.Property<byte>("Slot1")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("Slot2")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("Slot3")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Amulet");
                });

            modelBuilder.Entity("AthensWorkspace.Models.MHWs.AmuletPattern", b =>
                {
                    b.Property<byte>("Rare")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("Group1")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("Group2")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("Group3")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("Slot1")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("Slot2")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("Slot3")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Rare", "Group1", "Group2", "Group3", "Slot1", "Slot2", "Slot3");

                    b.ToTable("AmuletPattern");
                });

            modelBuilder.Entity("AthensWorkspace.Models.MHWs.AmuletSkillGroup", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint unsigned");

                    b.Property<short>("SkillId")
                        .HasColumnType("smallint");

                    b.Property<byte>("Level")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id", "SkillId");

                    b.ToTable("AmuletSkillGroup");
                });
#pragma warning restore 612, 618
        }
    }
}
